<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    protected $fillable = [
        'umur',
        'jantina',
        'agama',
        'lainAgamaDetail',
        'bangsa',
        'daerahBertugas',
        'status',
        'bilAnak',
        'bilIsiRumah',
        'tinggalBersamaPasangan',
        'bilBilikTidur',
        'education',
        'agensi',
        'kumpulanPerkhidmatan',
        'tarafJawatan',
        'skimPerkhidmatan',
        'gredJawatan',
        'gajiKasarBulanan',
        'gajiBersihBulanan',
        'kesukaranGaji',
        'tempohPerkhidmatanTahun',
        'tempohPerkhidmatanBulan',
        'masalahKesihatan',
        'masalahKesihatanDetail',
        'tempatTinggal',
        'tempatTinggalDetail',
        'tinggalBersama',
        'tinggalBersamaDetail',
        'kenderaanKerja',
        'kenderaanKerjaDetail',
        'B1',
        'B2',
        'B3',
        'B4',
        'B5',
        'B6',
        'B7',
        'B8',
        'B9',
        'B10',
        'B11',
        'B12',
        'B13',
        'B14',
        'B15',
        'B16',
        'B17',
        'B18',
        'C1',
        'C2',
        'D1',
        'E1',
        'E2',
        'E3',
        'E4',
        'E5',
        'E6',
        'F1',
        'F2',
        'F3',
        'F4',
        'F5',
        'F6',
        'G1',
        'G2',
        'G3',
        'G4',
        'G5',
        'G6',
        'G7',
        'G8',
        'G9',
        'G10',
        'H1',
        'H2',
        'H3',
        'H4',
        'H5',
        'H6',
        'H7',
        'H8',
        'H9',
        'H10',
        'H11',
        'H12',
        'H13',
        'H14',
        'H15',
        'H16',
        'H17',
        'H18',
        'H19',
        'H20',
        'H21',
        'H22',
        'H23',
        'H24',
        'H25',
        'H26',
        'H27',
        'H28',
        'H29',
        'H30',
        'H31',
        'H32',
        'H33',
        'H34',
        'H35',
        'I1',
        'I2',
        'I3',
        'J1',
        'J2',
        'J3',
        'J4',
        'J5',
        'J6',
        'J7',
        'J8',
        'J9',
        'J10',
        'K1',
        'K2',
        'K3',
        'K4',
        'K5',
        'K6',
        'K7',
        'K8',
        'K9',
        'K10',
        'L1',
        'L2',
        'L3',
        'L4',
        'M1',
        'M2',
        'M3',
        'N1',
        'N2',
        'N3',
        'N4',
        'O1',
        'O2',
        'O3',
        'O4',
        'O5',
        'P1',
        'P2',
        'Q1',
        'Q2',
        'Q3',
        'Q4',
        'komen',
        'cadangan',
        'uuid'
    ];


    protected $dates = [];
    public $timestamps = false;

    protected $appends = ['resource_url'];

    /* ************************ ACCESSOR ************************* */

    public function getResourceUrlAttribute()
    {
        return url('/admin/entries/' . $this->getKey());
    }
}
